export enum ErrorCodeEnum {
  INVALID_DATA = 'INVALID_DATA',
  INVALID_DRIVER = 'INVALID_DRIVER',
  NOT_FOUND = 'NOT_FOUND',
  DRIVER_NOT_FOUND = 'DRIVER_NOT_FOUND',
  NO_RIDES_FOUND = 'NO_RIDES_FOUND',
  INVALID_DISTANCE = 'INVALID_DISTANCE',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED'
}
