services:
  frontend:
    build: ./frontend
    container_name: frontend-shopper
    ports:
      - 80:80
    working_dir: /frontend
    depends_on: 
      - backend
  
  backend:
    build: ./backend
    container_name: backend-shopper
    ports:
      - 8080:8080
    working_dir: /backend
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://root:123456@localhost:3306/shopper

  db:
    image: mysql:8.0.21
    container_name: db-shopper
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
